---
title: EmoRy Coding Club master document 
author: |
 | Matt Malishev*, Desiree De Leon & Hasse Walum     
 |  
 | _Emory University, 1510 Clifton Road NE, Atlanta, GA, USA, 30322_
#bibliography:/Users/malishev/Documents/Melbourne Uni/Thesis_2016/library.bib
output:
  html_document:
    highlight: tango
    code_folding: show
    toc: yes
    toc_depth: 4
    number_sections: no
    toc_float: yes
params: 
  # dir: "/Users/malishev/Documents/Emory/admin/ecc/"
  date: !r Sys.Date()
  session: !r sessionInfo()  
  version: !r getRversion()
  email: "matthew.malishev@emory.edu"
  doi: https://github.com/darwinanddavis/EmoRyCodingClub
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

```{r echo = FALSE}
# library(rmarkdown)
# setwd("")
# f <- list.files()[1]
# render(f, output_format='pdf_document')
```

```{r, set-options, echo = FALSE, cache = FALSE}
options(width=100)
knitr::opts_chunk$set(
 eval = TRUE, # run all code
 # echo = FALSE, # show code chunks in output 
 comment = "",
 tidy.opts=list(width.cutoff=100), # set width of code chunks in output
 tidy=TRUE, # make output as tidy
 message = FALSE,  # mask all messages
 warning = FALSE, # mask all warnings 
 size="small" # set code chunk size
)

# https://github.com/ucb-stat133/stat133-fall-2016/blob/master/hws/hw02-tables-ggplot.Rmd
#knitr::opts_knit$set(root.dir=paste0(params$dir,"/")) # set working dir

#setwd(paste0(params$dir,"/")) # for running just in R not knitr
```

\newpage   

Date: `r params$date`  
R version: `r params$version`  
This document can be found at `r params$doi`  

<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- start body -->

\newpage  

#### Pre session  
1. assign 'hello world' to variable    
2. print to console  
3. run help page for 'print'  

#### First session  
```{r,eval=F}
install.packages()  
head()  
tail()
str()
plot()
df$Col1
df[,"Col1"]

# See call options for class
methods(class="estUDm")  

```

<!-- #### TOC     -->
<!-- What the session covers   -->
<!-- Dataset   -->
<!-- Showcase of what you'll learn by the end   -->



<!-- end body -->
<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
