---
Title: "Lesson 3"
header-includes: \usepackage{float}
always_allow_html: yes
output:
  html_document
params:
  lesson: !r paste0("Lesson ",3)
  title: "Lesson 3: Using lists and fitting lines and curves to data"      
---


```{r, setup, echo = FALSE, cache = FALSE, include = FALSE}
options(width=100)
knitr::opts_chunk$set(
  eval = FALSE, # run all code
  echo = TRUE, # show code chunks in output 
  tidy = TRUE, # make output as tidy
  message = FALSE,  # mask all messages
  warning = FALSE, # mask all warnings 
  comment = "",
  tidy.opts=list(width.cutoff=100), # set width of code chunks in output
  size="small" # set code chunk size
  )
```
\

<!-- install packages -->
```{r, load packages, eval=T, include=T, cache=F, message=F, warning=F, results='hide',echo=F}
packages <- c("ggplot2","ggthemes","dplyr","tidyverse","zoo","RColorBrewer","viridis","plyr")   
if (require(packages)) {
    install.packages(packages,dependencies = T)
    require(packages)
    # load tvthemes
    devtools::install_github("Ryo-N7/tvthemes")
}
lapply(packages,library,character.only=T)
```

<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- start body -->

# `r params$title`      
\  

Functions for `r params$lesson`    
```{r,eval=T, echo=F}
require(readr)
readLines("https://raw.githubusercontent.com/darwinanddavis/EmoRyCodingClub/master/functions_lesson2.txt")
```
\  

Packages for `r params$lesson`      
```{r,eval=T, echo=F}
require(readr)
readLines("https://raw.githubusercontent.com/darwinanddavis/EmoRyCodingClub/master/packages_lesson2.txt")
```
\    

# Agenda  

We'll be using [Ch 3 Data visualisation in `R` for Data Science](https://r4ds.had.co.nz/data-visualisation.html#statistical-transformations).  
Section 3.7.       

* Explore the super useful `list` structure  
* Plot bar charts and density distributions  

# Do First    

Recreate the below plot using the smaller NYC Airbnb dataset.  
```{r, echo=F, eval=T, out.width="100%"}
require(ggthemes)
# smaller csv file (16 cols)
url <- "http://data.insideairbnb.com/united-states/ny/new-york-city/2019-06-02/visualisations/listings.csv"
nyc <-  read_csv(url)
nyc <- nyc[nyc$id < 1000000,] # get smaller subet of data

ggplot(data = nyc, mapping = aes(x = minimum_nights, y = price)) +
  geom_point(aes(color=neighbourhood_group),show.legend = F) +
  facet_wrap(~ neighbourhood_group, nrow=length(nyc$neighbourhood_group)) +
  theme_classic()

```

